// <auto-generated />
using System;
using Atomlista.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Atomlista.Migrations
{
    [DbContext(typeof(AtomlistContext))]
    [Migration("20200210081629_Remove2Enty")]
    partial class Remove2Enty
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Atomlista.Models.Atom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AtomName")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.Property<int?>("BussinessOwnerId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("TechOwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("BussinessOwnerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("TechOwnerId");

                    b.ToTable("Atoms");
                });

            modelBuilder.Entity("Atomlista.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("CommentedProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommentedProductId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Atomlista.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("People");
                });

            modelBuilder.Entity("Atomlista.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BussinessOwnerId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int?>("TechOwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BussinessOwnerId");

                    b.HasIndex("TechOwnerId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Atomlista.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PeopleCount")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Atomlista.Models.Atom", b =>
                {
                    b.HasOne("Atomlista.Models.Person", "BussinessOwner")
                        .WithMany()
                        .HasForeignKey("BussinessOwnerId");

                    b.HasOne("Atomlista.Models.Product", null)
                        .WithMany("Atoms")
                        .HasForeignKey("ProductId");

                    b.HasOne("Atomlista.Models.Person", "TechOwner")
                        .WithMany()
                        .HasForeignKey("TechOwnerId");
                });

            modelBuilder.Entity("Atomlista.Models.Comment", b =>
                {
                    b.HasOne("Atomlista.Models.Product", "CommentedProduct")
                        .WithMany("Comments")
                        .HasForeignKey("CommentedProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Atomlista.Models.Person", b =>
                {
                    b.HasOne("Atomlista.Models.Team", null)
                        .WithMany("People")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("Atomlista.Models.Product", b =>
                {
                    b.HasOne("Atomlista.Models.Person", "BussinessOwner")
                        .WithMany()
                        .HasForeignKey("BussinessOwnerId");

                    b.HasOne("Atomlista.Models.Person", "TechOwner")
                        .WithMany()
                        .HasForeignKey("TechOwnerId");
                });
#pragma warning restore 612, 618
        }
    }
}
