// <auto-generated />
using System;
using Atomlista.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Atomlista.Migrations
{
    [DbContext(typeof(AtomlistContext))]
    [Migration("20200202103306_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Atomlista.Models.Atom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AtomName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BusinessOwnerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("TechOwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessOwnerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("TechOwnerId");

                    b.ToTable("Atoms");
                });

            modelBuilder.Entity("Atomlista.Models.BusinessOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("BusinessOwners");
                });

            modelBuilder.Entity("Atomlista.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CommentedProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CommentedProductId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Atomlista.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Atomlista.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BusinessOwnerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TechOwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusinessOwnerId");

                    b.HasIndex("TechOwnerId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Atomlista.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Atomlista.Models.TechOwner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("TechOwners");
                });

            modelBuilder.Entity("Atomlista.Models.Atom", b =>
                {
                    b.HasOne("Atomlista.Models.BusinessOwner", null)
                        .WithMany("Atoms")
                        .HasForeignKey("BusinessOwnerId");

                    b.HasOne("Atomlista.Models.Product", null)
                        .WithMany("Atoms")
                        .HasForeignKey("ProductId");

                    b.HasOne("Atomlista.Models.TechOwner", null)
                        .WithMany("Atoms")
                        .HasForeignKey("TechOwnerId");
                });

            modelBuilder.Entity("Atomlista.Models.BusinessOwner", b =>
                {
                    b.HasOne("Atomlista.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("Atomlista.Models.Comment", b =>
                {
                    b.HasOne("Atomlista.Models.Product", "CommentedProduct")
                        .WithMany("Comments")
                        .HasForeignKey("CommentedProductId");
                });

            modelBuilder.Entity("Atomlista.Models.Person", b =>
                {
                    b.HasOne("Atomlista.Models.Team", null)
                        .WithMany("People")
                        .HasForeignKey("TeamId");
                });

            modelBuilder.Entity("Atomlista.Models.Product", b =>
                {
                    b.HasOne("Atomlista.Models.BusinessOwner", null)
                        .WithMany("Products")
                        .HasForeignKey("BusinessOwnerId");

                    b.HasOne("Atomlista.Models.TechOwner", null)
                        .WithMany("Products")
                        .HasForeignKey("TechOwnerId");
                });

            modelBuilder.Entity("Atomlista.Models.TechOwner", b =>
                {
                    b.HasOne("Atomlista.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");
                });
#pragma warning restore 612, 618
        }
    }
}
